# Generated by Django 5.1.4 on 2026-03-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('image', models.ImageField(blank=True, null=True, upload_to='grups/', verbose_name='Imatge')),
                ('active', models.BooleanField(default=True, verbose_name='Actiu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Grup',
                'verbose_name_plural': 'Grups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GrupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('url', models.URLField(verbose_name='URL')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='socis.grup', verbose_name='Grup')),
            ],
            options={
                'verbose_name': 'Enllaç del grup',
                'verbose_name_plural': 'Enllaços del grup',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Soci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telèfon')),
                ('active', models.BooleanField(default=True, verbose_name='Actiu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('grup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socis', to='socis.grup', verbose_name='Grup')),
                ('instruments', models.ManyToManyField(blank=True, to='members.instrument', verbose_name='Instruments')),
            ],
            options={
                'verbose_name': 'Soci',
                'verbose_name_plural': 'Socis',
                'ordering': ['order', 'name'],
            },
        ),
    ]
