# Generated by Django 5.1.4 on 2026-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Títol')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('date', models.DateTimeField(verbose_name='Data i hora')),
                ('location', models.CharField(max_length=255, verbose_name='Lloc')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adreça')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imatge')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preu (€)')),
                ('url_tickets', models.URLField(blank=True, verbose_name='URL entrades')),
                ('published', models.BooleanField(default=False, verbose_name='Publicat')),
            ],
            options={
                'verbose_name': 'Esdeveniment',
                'verbose_name_plural': 'Esdeveniments',
                'ordering': ['date'],
            },
        ),
    ]
