# Generated by Django 5.1.4 on 2026-03-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['order', 'date'], 'verbose_name': 'Esdeveniment', 'verbose_name_plural': 'Esdeveniments'},
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre'),
        ),
    ]
