# Generated by Django 5.1.4 on 2026-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('home', 'Inici'), ('about', 'Sobre nosaltres')], max_length=20, unique=True, verbose_name='Pàgina')),
                ('title', models.CharField(max_length=255, verbose_name='Títol')),
                ('body', models.TextField(verbose_name='Cos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Imatge')),
            ],
            options={
                'verbose_name': 'Contingut de pàgina',
                'verbose_name_plural': 'Continguts de pàgines',
            },
        ),
    ]
