# Generated by Django 5.1.4 on 2026-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Títol')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Resum')),
                ('body', models.TextField(verbose_name='Cos')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Imatge')),
                ('published', models.BooleanField(default=False, verbose_name='Publicat')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de publicació')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícies',
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
    ]
