# Generated by Django 5.1.4 on 2026-03-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['order', '-pub_date'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícies'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ordre'),
        ),
    ]
