# Generated by Django 5.1.4 on 2026-03-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Instrument',
                'verbose_name_plural': 'Instruments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Foto')),
                ('active', models.BooleanField(default=True, verbose_name='Actiu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('joined_year', models.PositiveIntegerField(blank=True, null=True, verbose_name="Any d'incorporació")),
                ('instruments', models.ManyToManyField(blank=True, to='members.instrument', verbose_name='Instruments')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['order', 'name'],
            },
        ),
    ]
