# Generated by Django 5.1.4 on 2026-03-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='slug',
        ),
        migrations.AddField(
            model_name='member',
            name='carrec',
            field=models.CharField(blank=True, max_length=255, verbose_name='Càrrec'),
        ),
    ]
