# Generated by Django 5.1.4 on 2026-03-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Títol')),
                ('description', models.TextField(blank=True, verbose_name='Descripció')),
                ('category', models.CharField(choices=[('sala', 'Ús de sales'), ('normes', 'Normativa general'), ('altres', 'Altres')], default='sala', max_length=20, verbose_name='Categoria')),
                ('file', models.FileField(upload_to='protocols/', verbose_name='Arxiu')),
                ('published', models.BooleanField(default=True, verbose_name='Publicat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Protocol / Manual',
                'verbose_name_plural': 'Protocols i Manuals',
                'ordering': ['order', 'title'],
            },
        ),
    ]
