# Generated by Django 5.1.4 on 2026-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='category',
            field=models.CharField(choices=[('sala', 'Ús de sales'), ('normes', 'Normativa general'), ('formularis', 'Formularis'), ('altres', 'Altres')], default='sala', max_length=20, verbose_name='Categoria'),
        ),
    ]
